version: '3.8' 

services: 
rps-instance-1: 
	build: . 
	ports: - "5000:5000" # Map container's port 5000 to localhost's port 5000 
	environment: - INSTANCE_NAME=RPS1
rps-instance-2: 
	build: . 
	ports: - "5001:5000" # Map container's port 5000 to localhost's port 5001 
	environment: - INSTANCE_NAME=RPS2